export const config = {
  port: Number(process.env.PORT) || 3000,
  host: process.env.HOST || '0.0.0.0',
  baseUrl: process.env.BASE_URL || 'http://localhost:3000',
  hydraPublicUrl: process.env.HYDRA_PUBLIC_URL || '',
  hydraAdminUrl: process.env.HYDRA_ADMIN_URL || '',
  hydraApiKey: process.env.HYDRA_API_KEY || '',
  encryptionKey: process.env.ENCRYPTION_KEY || '',
  storageBackend: (process.env.STORAGE_BACKEND || 'file') as 'postgres' | 'file',
  databaseUrl: process.env.DATABASE_URL || '',
  dataDir: process.env.DATA_DIR || './data',
  maxAccountsPerUser: Number(process.env.MAX_ACCOUNTS_PER_USER) || 10,
  maxEmailsPerFetch: Number(process.env.MAX_EMAILS_PER_FETCH) || 100,
  imapTimeoutMs: Number(process.env.IMAP_TIMEOUT_MS) || 30000,
};
